codecov:
  max_report_age: 24
fixes:
  - "::/flutter_block"
# flags:
#   flutter_bloc:
#     paths:
#       - /flutter_bloc
#   states_rebuilder_example:
#     paths:
#       - /states_rebuilder_example
# coverage:
#   status:
#     project:
#       default:
#         flags:
#           - flutter_bloc
#           - states_rebuilder_example
#       projectA:
#         flags:
#           - flutter_bloc
#       projectB:
#         flags:
#           - states_rebuilder_example
